unique_ids:
  assets:
    standard-page.html: GGWIXR5ZWZVOSWTYNYYRX7LVEJV7NQNR
    theme.css: BWGWACENYZ4AYEZ7KGPQSSXG3TCU6ILG
  forms:
    Form1: FDIIWYKHT4CQNEBXFRRAGV7SCFH36KRV
  modules: {}
  scripts: {}
  server_modules: {}
